### ISSUE TITLE
Library Restructure

### ISSUE THREAD

**Issue by RigidStudios** [AetherInteractiveLtd/scribe#3]
I'd propose this kind of a structure, wherein @siriuslatte is currently working on @aethergames/mkscribe which is the *bytecode??/ast??/simplified??* Scribe generator. `ScribeRuntime` would be our actual runtime interpreter whilst `@aethergames/mkscribe` is our portable TypeScript-**only** converter to this alias format
```mermaid
graph
    direction LR
    subgraph "@rbxts/scribe"
        direction LR
        RT{{"ScribeRuntime"}} --> AST 

        subgraph "@aethergames/mkscribe"
            SC["Scanner"] --> TK["Tokenizer"]
            AST --> TK
        end
    end
    subgraph "@rbxts/questing"
        QM{{"QuestManager"}}==>RT
    end
```

**Comment by siriuslatte** [comment]
This is alright by me, closing this issue as it has been discussed previously.
